Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
images = []

for file in listdir("../images"):
    if ".png" in file:
        images.append("../images/" + file)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 3[0m
[1;32m      1[0m images [38;5;241m=[39m []
[0;32m----> 3[0m [38;5;28;01mfor[39;00m file [38;5;129;01min[39;00m [43mlistdir[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m../images[39;49m[38;5;124;43m"[39;49m[43m)[49m:
[1;32m      4[0m     [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124m.png[39m[38;5;124m"[39m [38;5;129;01min[39;00m file:
[1;32m      5[0m         images[38;5;241m.[39mappend([38;5;124m"[39m[38;5;124m../images/[39m[38;5;124m"[39m [38;5;241m+[39m file)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../images'

